### ISSUE TITLE
The Unforgivable - inconsistency between function and description

### ISSUE THREAD

**Issue by nvrfly** [hex3gc/Hex3Mod#15]
I've set the config value for the Unforgivable to 10 seconds interval.

I printed 6 copies of it during a run.
**Expected function:** every 10 seconds it triggers 6 times (???)
**Actual function:** the item triggers once every 1.5 seconds

Either the item description is false/misleading, or the item isn't working correctly.

A config option to alter the scaling would be really handy.

**Comment by hex3gc** [comment]
Changed for next update, that wording will be a lot clearer.
