### ISSUE TITLE
Create a cap for hermit item

### ISSUE THREAD

**Issue by Edge363** [hex3gc/Hex3Mod#3]
Currently, certain survivors can too fully utilize the hermit item, effectively making themselves invincible with just the one item. 

Ex. Double nail gun mul-t, mobile turrets, and sometimes the commando can become 4-10 times tankier with the one item.

**Comment by hex3desu** [comment]
I have plans for changing The Hermit into a more reasonable damage reduction soon. What will likely happen is it'll inflict a stacking debuff on enemies that reduces *their* damage (up to 75%), which should balance it out by being worse against hordes of enemies (and Mithrix who cleanses his debuffs often)

**Comment by Edge363** [comment]
I really like this current incarnation, just the balancing seems off. I think this is a cool item, and I'd hate to see you get rid of it! Of course it's your mod, and it's incredible so far, so I'm sure you'll keep doing great things.

Maybe make a alchemy set red item? That is a parallel to chrono bauble, but it lowers their attack speed/damage on hit to make use of that debuff idea? Thanks for responding!
